# Generated by Django 3.0.6 on 2022-06-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='User1',
        ),
    ]
